# .cpanel.yml file to deploy the bearbros directory for hosting the website on cPanel

---
deployment:
  tasks:
    - export DEPLOYPATH=~/Users/meiliebearden/Documents/coding/quickie/helloWorld/bearbros
    - mkdir -p $DEPLOYPATH
    - cp -R * $DEPLOYPATH